version: "3"

services:
  sonarqube:
    image: sonarqube:8-community
    container_name: sonarqubeweb
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonarqube   
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - sonarqube_data:/opt/sonarqube/data      
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - database
    networks:
      - sonarqubenet
  database:
    image: postgres:12.1
    container_name: sonarqubedb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    ports:
        - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - sonarqubenet
networks:
    sonarqubenet:
        driver: bridge
volumes:
  postgresql:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
